import type { Metadata } from "next";
import "./globals.css";
import { Cabin_Sketch } from 'next/font/google';

const cabinSketch = Cabin_Sketch({
  weight: ['700'],  
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cabinSketch.className}>
        {children}
      </body>
    </html>
  );
}
